"""AI Marketing Studio generator (Doc 2.13 / 10.11).

Turns a shop's logo and photos into postable assets. Generation is queued rather
than done inline because composing a slideshow video takes long enough that a
synchronous request would time out on a shop's phone connection.

Posters and slideshows are composited with Pillow (see `app.ai_studio.compose`)
rather than generated by a model: Doc 2.13 puts true AI video in Phase 3, and a
poster is not a generative problem. So this worker needs no API key, runs offline
and cannot fail at 3am because a vendor is down.

When R2 is not configured — a developer's laptop, most CI runs — the text assets
are still produced and the file assets come back with a null `file_url`. That is
deliberate: captions are the part an owner can use on day one, and a row that
says "not produced yet" shows "generating" rather than a broken image.

Swapping in a real model later means replacing `_generate_visual` only.
"""

import io
import uuid
from typing import Any

from celery import shared_task
from sqlalchemy import select

from app.ai_studio.compose import (
    DEFAULT_BRAND_COLOR,
    compose_poster,
    compose_slideshow_frames,
    encode_slideshow,
    placeholder_image,
)
from app.core.config import settings
from app.core.storage import _client, storage_configured
from app.models.ai import AIAsset, AIProject
from app.models.tenant import Business
from app.workers.db import run_async, session_scope

# Doc 2.13 requires at least 5 photos before generating — fewer and the result
# is a template with a logo on it, which the owner would have to redo anyway.
MIN_PHOTOS = 5

# The asset types a project gets. Chosen to match how Kenyan salons actually
# post: WhatsApp status for same-day promos, Facebook/Instagram for reach, and a
# short caption they can paste anywhere.
ASSET_TYPES = (
    "fb_post",
    "ig_post",
    "whatsapp_status",
    "tiktok_caption",
    "poster",
    "slideshow_video",
)


def _generate_captions(project: AIProject) -> dict[str, str]:
    """Caption text for the text assets. No model required, no API key."""
    name = project.shop_name
    return {
        "fb_post": (
            f"Fresh cuts, fair prices, no appointment drama. {name} is open — "
            f"walk in or book ahead. 💈"
        ),
        "ig_post": (
            f"{name} ✨ Book your next look with us. Tag someone who is due for "
            f"a refresh."
        ),
        "whatsapp_status": (
            f"{name} is open today. Walk in any time — we'll put you in the chair."
        ),
        "tiktok_caption": f"New week, new cut. {name} 🪒 #nairobi #barber",
    }


def _brand_color(business) -> tuple[int, int, int]:
    """The business's brand colour, or the studio default.

    Businesses store no colour of their own yet, so this is the one place to
    change when that arrives. Parsed defensively: a malformed value in the
    database must not fail a whole generation run.
    """
    raw = getattr(business, "brand_color", None) if business else None
    if isinstance(raw, str) and raw.startswith("#") and len(raw) == 7:
        try:
            return (int(raw[1:3], 16), int(raw[3:5], 16), int(raw[5:7], 16))
        except ValueError:
            pass
    return DEFAULT_BRAND_COLOR


def _upload(key: str, data: bytes, content_type: str) -> str | None:
    """Put bytes in R2 and return the key, or None if storage is unavailable.

    The asset row stores the key, not a signed URL: a signed URL expires in
    minutes, and a row holding an expired link shows a broken image tomorrow.
    The client signs on read.
    """
    if not storage_configured():
        return None
    try:
        _client().put_object(
            Bucket=settings.r2_bucket,
            Key=key,
            Body=data,
            ContentType=content_type,
            # Public assets only ever reach the owner, and only via a signed URL.
            CacheControl="private, max-age=0, no-store",
        )
        return key
    except Exception:
        # A failed upload must not abort the captions: the text is the part the
        # owner can use immediately, even if the poster did not render.
        return None


def _fetch(key: str) -> bytes | None:
    """Download a photo from R2, or None if it is missing or unreadable."""
    if not storage_configured() or not key:
        return None
    try:
        response = _client().get_object(Bucket=settings.r2_bucket, Key=key)
        return response["Body"].read()
    except Exception:
        return None


def _generate_visual(
    asset_type: str,
    photos: list[str],
    logo_key: str | None,
    shop_name: str,
    tagline: str,
    business,
) -> str | None:
    """Compose the poster or slideshow and upload it. Returns an R2 key.

    Doc 2.13 puts true generative video in Phase 3, and a poster is not a
    generative problem — it is a photo, a logo, some text and a colour. So this
    composites with Pillow instead of calling a model. That runs offline, costs
    nothing per poster, and cannot fail because a vendor is down.

    Returns None when the file could not be produced, which leaves a row with a
    null `file_url`. That is honest and the UI shows "generating" rather than a
    broken image.
    """
    if asset_type not in ("poster", "slideshow_video"):
        return None

    brand = _brand_color(business)
    image_photos = [data for data in (_fetch(k) for k in photos) if data]
    if not image_photos:
        # Better a branded card than a null: the owner sees something that looks
        # deliberate, and the key is real so it can be replaced on regeneration.
        data = placeholder_image()
        return _upload(
            f"{business.id if business else 'unknown'}/ai/{uuid.uuid4().hex}.jpg",
            data,
            "image/jpeg",
        )

    logo = _fetch(logo_key) if logo_key else None

    if asset_type == "poster":
        poster = compose_poster(
            image_photos[0], shop_name, tagline, brand_color=brand, logo=logo
        )
        buffer = io.BytesIO()
        poster.image.save(buffer, format="JPEG", quality=88)
        return _upload(
            f"{business.id if business else 'unknown'}/ai/{uuid.uuid4().hex}.jpg",
            buffer.getvalue(),
            "image/jpeg",
        )

    frames = compose_slideshow_frames(
        image_photos, shop_name, tagline, brand_color=brand
    )
    gif = encode_slideshow(frames)
    if not gif:
        return None
    return _upload(
        f"{business.id if business else 'unknown'}/ai/{uuid.uuid4().hex}.gif",
        gif,
        "image/gif",
    )


async def _generate(project_id: str) -> dict:
    produced: list[str] = []
    unproduced: list[str] = []

    async with session_scope() as db:
        project = await db.scalar(select(AIProject).where(AIProject.id == project_id))
        if not project or project.status == "ready":
            return {"assets": 0, "skipped": "already generated"}

        project.status = "processing"
        await db.flush()

        photos: list[Any] = project.photo_urls or []
        if len(photos) < MIN_PHOTOS:
            # Back to `uploaded` rather than `ready`: the owner needs to add
            # photos and re-trigger, and the project must not read as done.
            project.status = "uploaded"
            return {
                "assets": 0,
                "skipped": f"needs {MIN_PHOTOS} photos, has {len(photos)}",
            }

        business = await db.scalar(
            select(Business).where(Business.id == project.business_id)
        )
        shop_name = business.name if business else project.shop_name
        project.shop_name = shop_name

        captions = _generate_captions(project)

        for asset_type in ASSET_TYPES:
            text = captions.get(asset_type)
            file_url = _generate_visual(
                asset_type,
                photos=photos,
                logo_key=project.logo_url,
                shop_name=shop_name,
                tagline=captions.get("ig_post", ""),
                business=business,
            )
            db.add(
                AIAsset(
                    project_id=project.id,
                    asset_type=asset_type,
                    content_text=text,
                    file_url=file_url,
                )
            )
            (produced if file_url else unproduced).append(asset_type)

        project.status = "ready"

    return {
        "assets": len(ASSET_TYPES),
        "captions": produced,
        "awaiting_visual_backend": unproduced,
    }


@shared_task(bind=True, max_retries=2, default_retry_delay=60)
def generate_assets(self, project_id: str):
    """Generate one project's assets. Idempotent: a `ready` project is skipped."""
    try:
        return run_async(lambda: _generate(project_id))
    except Exception as exc:
        raise self.retry(exc=exc)
